server:
  port: 8080

spring:
  application:
    name: websocket-fizzbuzz

  thymeleaf:
    cache: false

logging:
  level:
    org.example.spring.websocket: DEBUG
    # Show WebSocket disconnection events
    org.springframework.web.socket: INFO
    org.springframework.messaging: INFO
    # Keep important WebSocket errors visible
    org.springframework.web.socket.sockjs: INFO
    org.springframework.web.socket.messaging: INFO
    # Show STOMP protocol events
    org.springframework.web.socket.messaging.StompSubProtocolHandler: INFO
