server:
  port: 8080

spring:
  application:
    name: security-app

  # Thymeleaf Configuration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  # Database Configuration
  datasource:
    url: jdbc:h2:mem:securitydb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  # Cache Configuration
  cache:
    type: simple
    cache-names: users
    simple:
      time-to-live: 28800000  # 8 hours in milliseconds

# Security Configuration
logging:
  level:
    org.springframework.security: DEBUG
    com.example.spring.security: DEBUG
    org.springframework.web: DEBUG
