server:
  port: 8080

spring:
  application:
    name: activemq-example

  activemq:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30000
    packages:
      trust-all: true

  jms:
    cache:
      enabled: true
      session-cache-size: 10
    listener:
      acknowledge-mode: auto

  # Global Jackson configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
      fail-on-null-for-primitives: false
    default-property-inclusion: non_null

logging:
  level:
    org.foo.activemq: DEBUG
    org.springframework.jms: DEBUG
    org.apache.activemq: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
